import { SignIn, SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

import { api } from "~/utils/api";

const Home: NextPage = () => {
  // const hello = api.example.hello.useQuery({ text: "from tRPC" });

  const user = useUser();

  // This line has potential to do something fancy with tRPC
  // You don't want the user connecting directly to a database especially when
  // using something like Vercel. Here we use tRPC as a different server to access data.
  /* The reason we use tRPC is so we can separate the data, where the users see it on
     index.tsx and we can access via the posts.ts Routers like its on the same machine.
  */
  const {data} = api.posts.getAll.useQuery();

  // console.log(hello.data);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center text-white bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div>
          {!user.isSignedIn && <SignInButton/>}{!!user.isSignedIn && <SignOutButton />}
        </div>
        <div>
          {/* Don't forget about the key, as React uses it to keep track of what needs to be updated. */}
          {data?.map((post) => (<div key={post.id}>{post.content}</div>))}
        </div>
      </main>
    </>
  );
};

export default Home;
